server:
  port: 8081  # 强制指定端口为8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chat
    username: root
    password: 19805601056Bkj@@
    driver-class-name: com.mysql.cj.jdbc.Driver

  ai:
    openai:
      api-key: #就不告诉你
      base-url: #就不告诉你


  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:${file.upload-dir} # 将上传目录配置为静态资源路径

file:
  upload-dir: ./uploads # 上传目录路径
